SEED = 0
CACHING = False

# Flat 2D plate noise.
PLT_REFERENCE_SCALE = 0.00015
PLT_SCALE = 0.00015
PLT_STRETCHING = 0.2
PLT_ROUGHNESS = 5
PLT_BDR_SHAPE = 0.0005
PLT_SHAPE = 0.45
PLATE_GEOMETRY_EPSILON = 1e-9
PLATE_GEOMETRY_DEDUPE_EPSILON = 1e-8
PLATE_GEOMETRY_PADDING_CELLS = 2.0

# Plate classes.
OCEANIC_PLATE_ID = 0
CONTINENTAL_PLATE_ID = 1
CONTINENTS_FRACT = 0.85

# Continent field defaults.
SEA_LEVEL_FRACTION = 0.35
OCN_HGT = 0.0
CONT_HGT = 0.2
OCN_BLD_WIDTH = 0.75
OCN_BLD_EXP = 3.0

LAND_AMP = 1.0
LAND_WIDTH = 2
LAND_INT_SKEW = 1.0
LAND_BDR_SKEW = 4.0
LAND_PLT_COVERAGE = 0.6

ISLS_AMP = SEA_LEVEL_FRACTION
ISLS_WIDTH = 0.1
ISLS_INT_SKEW = 6.0
ISLS_BDR_SKEW = 2.0
ISLS_PLT_COVERAGE = 0.65

MNTS_AMP = 1.0
MNTS_WIDTH = 0.3
MNTS_INT_SKEW = 2.0
MNTS_BDR_SKEW = 2.0
MNTS_PLT_COVERAGE = 0.5

PLTU_AMP = 1.0
SHDW_AMP = 5.0
PLATEAU_BRIDGE_WIDTH = 0.15
PLATEAU_CLOSING_FADE_WIDTH = 0.25

# Terrain height sampling.
BASE_TERRAIN_LAND_SCALE = 1.0
BASE_TERRAIN_MOUNTAIN_SCALE = 0.35

# River generation defaults.
RIVER_GRID_RES = 100
RIVER_COUNT = 50
SOURCE_MIN_HEIGHT = 0.5
MIN_SOURCE_SPACING = 5
STEP_SIZE = 2
MAX_RIVER_STEPS = 160
RIVR_BORDER_DIST = 100.0
RIVR_DIST_WIDTH = 100.0
RIVR_LAKE_RADIUS = 150.0
RIVR_HGHT_SLOPE_DROP = 0.005
RIVER_BLEND_EXP = 1.5
RIVER_MIN_DROP = 1e-6
RIVER_PATH_DISTANCE_WEIGHT = 1e-5
RIVER_DISTANCE_FIELD_POWER = 1.0
RIVER_LAKE_SURFACE_MARGIN_DISTANCE = 0.07 * RIVR_DIST_WIDTH
RIVER_LAKE_NODE_HEIGHT_FADE_DISTANCE = RIVR_DIST_WIDTH
RIVER_HEIGHT_BLEND_DISTANCE = RIVR_DIST_WIDTH
RIVER_REGION_EPSILON = 1e-9
RIVER_POINT_IN_REGION_EPSILON = 1e-7
RIVER_REGION_CANDIDATE_RADIUS_MULTIPLIER = 2.0
RIVER_REGION_NEAREST_SEGMENT_COUNT = 12
RIVER_VIEW_MARGIN_FRACTION = 0.08

# Interactive terrain visualizer.
VISUALIZER_PLT_OWNER_IDX = (1, 0)
TERRAIN_VIEW_RIVERS = True
TERRAIN_RESOLUTION = 100
TERRAIN_PLATE_CELLS = 1.0
TERRAIN_HEIGHT_SCALE = 0.1
TERRAIN_SHIFT_CELLS = 0.05
TERRAIN_MOVE_CELLS_PER_SECOND = 1.0
TERRAIN_LOAD_REQUEST_INTERVAL_SECONDS = 0.12
TERRAIN_WINDOW_WIDTH = 1000
TERRAIN_WINDOW_HEIGHT = 760
TERRAIN_FPS = 100
TERRAIN_INITIAL_YAW_DEG = -38.0
TERRAIN_INITIAL_ELEVATION_DEG = 24.0
TERRAIN_MIN_ELEVATION_DEG = 8.0
TERRAIN_MAX_ELEVATION_DEG = 72.0
TERRAIN_MOUSE_ROTATION_SPEED = 0.006
TERRAIN_RIVER_ACTIVE_RADIUS = 1
TERRAIN_RIVER_HEIGHT_OFFSET = 0.012
TERRAIN_SCREEN_SCALE = 0.34
TERRAIN_SCREEN_BASELINE = 0.68
TERRAIN_VERTICAL_SCALE = 0.88
TERRAIN_BACKGROUND_COLOR = (12, 15, 20)
TERRAIN_EDGE_COLOR = (210, 218, 230)
TERRAIN_HUD_TEXT_COLOR = (225, 230, 235)
RIVER_CHANNEL_COLOR = (24, 112, 214)
RIVER_CHANNEL_HIGHLIGHT_COLOR = (188, 229, 255)
RIVER_CHANNEL_WIDTH = 2
RIVER_CHANNEL_HIGHLIGHT_WIDTH = 1
RIVER_SOURCE_COLOR = (248, 250, 252)
RIVER_SOURCE_RADIUS = 2
RIVER_LOCAL_MINIMUM_COLOR = (255, 176, 64)
RIVER_LOCAL_MINIMUM_RADIUS = 2
RIVER_SEA_OUTLET_COLOR = (72, 190, 255)
RIVER_SEA_OUTLET_RADIUS = 2
RIVER_NODE_COLOR = (34, 148, 242)
RIVER_NODE_RADIUS = 3
